[project]
dependencies = [
    'requests >= 2.28.1',
]
name = "properly"
version = "0.0.0"

[project.optional-dependencies]
dev = [
    'pytest >= 7.2.0',
    'mypy >= 0.982',
]

#[build-system]
## TODO: Properly.
#requires = [
#    "setuptools ~= 58.0",
#    "cython ~= 0.29.0"
#]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
python_files = [
    "*_test.py", "*Test.py",
]
pythonpath = "src"
