name: Python application

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Type check with mypy
        run: |
          cd src
          mypy properly
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
      - name: Build wheel
        run: hatch build
      # dist/properly-0.1.dev1+g276bc25-py3-none-any.whl

      - uses: actions/upload-artifact@v2
        with:
          name: properly
          path: dist/properly-0.1.dev1+g276bc25-py3-none-any.whl
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: properly
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install wheel itself
        run: |
          python -m pip install wheel
      - name: Install the wheel
        run: |
          ls 
          python -m wheel install dist/properly-0.1.dev1+g276bc25-py3-none-any.whl
      
